name: grc-platform
channels:
  - conda-forge
  - pytorch
  - huggingface
  - defaults
dependencies:
  # Python version
  - python=3.11
  
  # Core Python packages
  - pip
  - setuptools
  - wheel
  
  # System dependencies
  - gcc
  - gxx
  - make
  - cmake
  - pkg-config
  
  # Database and caching
  - redis
  - postgresql
  
  # Scientific computing
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy
  - scikit-learn=1.3.0
  
  # Deep learning frameworks
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Adjust based on your CUDA version
  
  # Hugging Face ecosystem
  - transformers>=4.35.0
  - tokenizers>=0.14.0
  - datasets>=2.14.0
  - accelerate>=0.24.0
  - safetensors>=0.4.0
  - huggingface-hub>=0.17.0
  
  # NLP and text processing
  - nltk>=3.8.1
  - spacy>=3.7.0
  - sentence-transformers>=2.2.2
  
  # Development tools
  - jupyter
  - ipykernel
  - black
  - flake8
  - mypy
  - pytest
  - pytest-asyncio
  - pre-commit
  
  # Monitoring and observability
  - prometheus-client>=0.21.1
  
  # Pip dependencies (packages not available in conda)
  - pip:
    # FastAPI and web framework
    - fastapi>=0.115.6
    - uvicorn[standard]>=0.32.1
    - pydantic>=2.9.2
    - pydantic-settings>=2.6.1
    
    # Database ORM and drivers
    - sqlalchemy>=2.0.35
    - psycopg2-binary>=2.9.10
    - alembic>=1.14.0
    
    # Redis clients
    - redis>=5.2.1
    - aioredis>=2.0.1
    
    # AI/ML and LLM libraries
    - openai>=1.54.4
    - langchain>=0.3.7
    - langchain-community>=0.3.7
    - chromadb>=0.5.23
    - ollama>=0.4.2
    
    # HTTP clients
    - httpx>=0.28.1
    - requests>=2.32.3
    
    # Configuration and environment
    - python-dotenv>=1.0.1
    - aiofiles>=24.1.0
    
    # Security and authentication
    - cryptography>=44.0.0
    - passlib[bcrypt]>=1.7.4
    - python-jose[cryptography]>=3.3.0
    - python-multipart>=0.0.12
    
    # Templating and markup
    - jinja2>=3.1.4
    - markdown>=3.7.0
    
    # Async messaging
    - asyncio-mqtt>=0.16.2
    
    # Caching and optimization
    - cachetools>=5.3.0
    
    # Development and testing
    - pytest-cov>=6.0.0
    - pytest-mock>=3.14.0
    
    # Monitoring
    - grafana-api>=1.0.3
